defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: hoccer_accounts

test:
  <<: *defaults
  database: new_api_test

# set these environment variables on your prod server
production:
  <<: *defaults
  #host: <%= ENV['MONGOID_HOST'] %>
  #port: <%= ENV['MONGOID_PORT'] %>
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  database: hoccer_accounts
